In [8]:
# Initial imports
import pandas as pd
import hvplot.pandas
from path import Path
import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
# Load in the data
file_path = "C:/Users/14109/code/Beer_Restaurant_Success/cleaned_beer_dataset.csv"
permit_df = pd.read_csv(file_path, index_col=0)

permit_df.head()

,Permit #,Status,Permit Type,Permit SubType,Permit Sub Type Description,Date Entered,Date Issued,Parcel,Business Name,Address,City,State,Zip,Mapped Location
0,19-25846,ISSUED,BBPERMIT,ONSALES,BB - On Site Sales,01/24/2019,06/03/2019,16300030200,EXO-TIKKA INDIAN CUSINE,5385 MT VIEW RD,ANTIOCH,TN,37013.0,"5385 MT VIEW RD\r\nANTIOCH, TN 37013\r\n(36.04..."
1,16-20340,ISSUED,BBPERMIT,ONSALES,BB - On Site Sales,05/18/2016,09/23/2016,09114025000,Las Palmas Mexican Restaurant,5821 Charlotte PIKE,Nashville,TN,37209.0,"5821 Charlotte PIKE\r\nNashville, TN 37209\r\n..."
2,17-00205,ISSUED,BBPERMIT,WHOLESALES,"BB - Wholesale, Distributor",11/03/2016,07/10/2017,09112001600,Fat Bottom Brewing,800 44th AVE N,Nashville,TN,37209.0,"800 44th AVE N\r\nNashville, TN 37209\r\n(36.1..."
3,19-25920,ISSUED,BBPERMIT,ONOFFSALES,BB - On & Off Site Sales,03/06/2019,06/13/2019,11714013900,NASHVILLE CIGAR,4001 HILLSBORO PIKE,NASHVILLE,TN,37215.0,"4001 HILLSBORO PIKE\r\nNASHVILLE, TN 37215\r\n..."
4,19-25985,ISSUED,BBPERMIT,ONOFFSALES,BB - On & Off Site Sales,04/22/2019,06/13/2019,08305018200,TAILGATE BREWERY EAST NASHVILLE,811 GALLATIN AVE,NASHVILLE,TN,37206.0,"811 GALLATIN AVE\r\nNASHVILLE, TN 37206\r\n(36..."