In [1]:
# Dependencies
import pandas as pd

In [2]:
# csv to dataFrame
demo_df = pd.read_csv("../Beer_Restaurant_Success/Resources/demographics_by_zip.csv")
edu_df = pd.read_csv("../Beer_Restaurant_Success/Resources/education_by_zip.csv")
income_df = pd.read_csv("../Beer_Restaurant_Success/Resources/income_by_zip.csv")

In [3]:
# inspect demo_df headers
demo_df.head()

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,...,DP05_0087PE,DP05_0087PM,DP05_0088E,DP05_0088M,DP05_0088PE,DP05_0088PM,DP05_0089E,DP05_0089M,DP05_0089PE,DP05_0089PM
0,id,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Percent!!SEX AND AGE!!Total population!!Male,Percent Margin of Error!!SEX AND AGE!!Total po...,...,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...","Margin of Error!!CITIZEN, VOTING AGE POPULATIO...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...","Margin of Error!!CITIZEN, VOTING AGE POPULATIO...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P..."
1,8600000US37013,ZCTA5 37013,97939,2456,97939,(X),47658,1617,48.7,1.1,...,59479,(X),27984,1026,47.0,1.4,31495,1192,53.0,1.4
2,8600000US37027,ZCTA5 37027,56117,765,56117,(X),27888,915,49.7,1.3,...,39146,(X),19094,743,48.8,1.2,20052,480,51.2,1.2
3,8600000US37067,ZCTA5 37067,29543,1010,29543,(X),14462,610,49.0,1.4,...,20448,(X),9573,498,46.8,1.6,10875,582,53.2,1.6
4,8600000US37072,ZCTA5 37072,31492,763,31492,(X),15327,585,48.7,1.5,...,24099,(X),11489,456,47.7,1.6,12610,573,52.3,1.6

In [4]:
# change header to 1st row demo_df
new_header = demo_df.iloc[0] # assign index 0 as variable
demo_df = demo_df[1:] # drops orriginal headers
demo_df.columns = new_header # assigns header to previous index 0
demo_df.head()

,id,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population,Percent Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population!!Male,Percent!!SEX AND AGE!!Total population!!Male,Percent Margin of Error!!SEX AND AGE!!Total population!!Male,...,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female","Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
1,8600000US37013,ZCTA5 37013,97939,2456,97939,(X),47658,1617,48.7,1.1,...,59479,(X),27984,1026,47.0,1.4,31495,1192,53.0,1.4
2,8600000US37027,ZCTA5 37027,56117,765,56117,(X),27888,915,49.7,1.3,...,39146,(X),19094,743,48.8,1.2,20052,480,51.2,1.2
3,8600000US37067,ZCTA5 37067,29543,1010,29543,(X),14462,610,49.0,1.4,...,20448,(X),9573,498,46.8,1.6,10875,582,53.2,1.6
4,8600000US37072,ZCTA5 37072,31492,763,31492,(X),15327,585,48.7,1.5,...,24099,(X),11489,456,47.7,1.6,12610,573,52.3,1.6
5,8600000US37076,ZCTA5 37076,40161,1183,40161,(X),19600,774,48.8,1.5,...,30384,(X),14353,602,47.2,1.6,16031,650,52.8,1.6

In [5]:
# view all headers
list(demo_df.columns.values)

['id',
 'Geographic Area Name',
 'Estimate!!SEX AND AGE!!Total population',
 'Margin of Error!!SEX AND AGE!!Total population',
 'Percent!!SEX AND AGE!!Total population',
 'Percent Margin of Error!!SEX AND AGE!!Total population',
 'Estimate!!SEX AND AGE!!Total population!!Male',
 'Margin of Error!!SEX AND AGE!!Total population!!Male',
 'Percent!!SEX AND AGE!!Total population!!Male',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Male',
 'Estimate!!SEX AND AGE!!Total population!!Female',
 'Margin of Error!!SEX AND AGE!!Total population!!Female',
 'Percent!!SEX AND AGE!!Total population!!Female',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Female',
 'Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)',
 'Margin of Error!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)',
 'Percent!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)',
 'Estimate!!SEX AND AGE!!Total population!!Under 5 years',
 'Margin of Error!!SEX AND AGE!!Total population!!Under 5 years',
 'Percent!!SEX AND AGE!!Total population!!Under 5 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Under 5 years',
 'Estimate!!SEX AND AGE!!Total population!!5 to 9 years',
 'Margin of Error!!SEX AND AGE!!Total population!!5 to 9 years',
 'Percent!!SEX AND AGE!!Total population!!5 to 9 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!5 to 9 years',
 'Estimate!!SEX AND AGE!!Total population!!10 to 14 years',
 'Margin of Error!!SEX AND AGE!!Total population!!10 to 14 years',
 'Percent!!SEX AND AGE!!Total population!!10 to 14 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!10 to 14 years',
 'Estimate!!SEX AND AGE!!Total population!!15 to 19 years',
 'Margin of Error!!SEX AND AGE!!Total population!!15 to 19 years',
 'Percent!!SEX AND AGE!!Total population!!15 to 19 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!15 to 19 years',
 'Estimate!!SEX AND AGE!!Total population!!20 to 24 years',
 'Margin of Error!!SEX AND AGE!!Total population!!20 to 24 years',
 'Percent!!SEX AND AGE!!Total population!!20 to 24 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!20 to 24 years',
 'Estimate!!SEX AND AGE!!Total population!!25 to 34 years',
 'Margin of Error!!SEX AND AGE!!Total population!!25 to 34 years',
 'Percent!!SEX AND AGE!!Total population!!25 to 34 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!25 to 34 years',
 'Estimate!!SEX AND AGE!!Total population!!35 to 44 years',
 'Margin of Error!!SEX AND AGE!!Total population!!35 to 44 years',
 'Percent!!SEX AND AGE!!Total population!!35 to 44 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!35 to 44 years',
 'Estimate!!SEX AND AGE!!Total population!!45 to 54 years',
 'Margin of Error!!SEX AND AGE!!Total population!!45 to 54 years',
 'Percent!!SEX AND AGE!!Total population!!45 to 54 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!45 to 54 years',
 'Estimate!!SEX AND AGE!!Total population!!55 to 59 years',
 'Margin of Error!!SEX AND AGE!!Total population!!55 to 59 years',
 'Percent!!SEX AND AGE!!Total population!!55 to 59 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!55 to 59 years',
 'Estimate!!SEX AND AGE!!Total population!!60 to 64 years',
 'Margin of Error!!SEX AND AGE!!Total population!!60 to 64 years',
 'Percent!!SEX AND AGE!!Total population!!60 to 64 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!60 to 64 years',
 'Estimate!!SEX AND AGE!!Total population!!65 to 74 years',
 'Margin of Error!!SEX AND AGE!!Total population!!65 to 74 years',
 'Percent!!SEX AND AGE!!Total population!!65 to 74 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!65 to 74 years',
 'Estimate!!SEX AND AGE!!Total population!!75 to 84 years',
 'Margin of Error!!SEX AND AGE!!Total population!!75 to 84 years',
 'Percent!!SEX AND AGE!!Total population!!75 to 84 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!75 to 84 years',
 'Estimate!!SEX AND AGE!!Total population!!85 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!85 years and over',
 'Percent!!SEX AND AGE!!Total population!!85 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!85 years and over',
 'Estimate!!SEX AND AGE!!Total population!!Median age (years)',
 'Margin of Error!!SEX AND AGE!!Total population!!Median age (years)',
 'Percent!!SEX AND AGE!!Total population!!Median age (years)',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Median age (years)',
 'Estimate!!SEX AND AGE!!Total population!!Under 18 years',
 'Margin of Error!!SEX AND AGE!!Total population!!Under 18 years',
 'Percent!!SEX AND AGE!!Total population!!Under 18 years',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!Under 18 years',
 'Estimate!!SEX AND AGE!!Total population!!16 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!16 years and over',
 'Percent!!SEX AND AGE!!Total population!!16 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!16 years and over',
 'Estimate!!SEX AND AGE!!Total population!!18 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!18 years and over',
 'Percent!!SEX AND AGE!!Total population!!18 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!18 years and over',
 'Estimate!!SEX AND AGE!!Total population!!21 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!21 years and over',
 'Percent!!SEX AND AGE!!Total population!!21 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!21 years and over',
 'Estimate!!SEX AND AGE!!Total population!!62 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!62 years and over',
 'Percent!!SEX AND AGE!!Total population!!62 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!62 years and over',
 'Estimate!!SEX AND AGE!!Total population!!65 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!65 years and over',
 'Percent!!SEX AND AGE!!Total population!!65 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over',
 'Estimate!!SEX AND AGE!!Total population!!18 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!18 years and over',
 'Percent!!SEX AND AGE!!Total population!!18 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!18 years and over',
 'Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male',
 'Margin of Error!!SEX AND AGE!!Total population!!18 years and over!!Male',
 'Percent!!SEX AND AGE!!Total population!!18 years and over!!Male',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!18 years and over!!Male',
 'Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female',
 'Margin of Error!!SEX AND AGE!!Total population!!18 years and over!!Female',
 'Percent!!SEX AND AGE!!Total population!!18 years and over!!Female',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!18 years and over!!Female',
 'Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)',
 'Margin of Error!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)',
 'Percent!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)',
 'Estimate!!SEX AND AGE!!Total population!!65 years and over',
 'Margin of Error!!SEX AND AGE!!Total population!!65 years and over',
 'Percent!!SEX AND AGE!!Total population!!65 years and over',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over',
 'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male',
 'Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Male',
 'Percent!!SEX AND AGE!!Total population!!65 years and over!!Male',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Male',
 'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female',
 'Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Female',
 'Percent!!SEX AND AGE!!Total population!!65 years and over!!Female',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Female',
 'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)',
 'Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)',
 'Percent!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)',
 'Estimate!!RACE!!Total population',
 'Margin of Error!!RACE!!Total population',
 'Percent!!RACE!!Total population',
 'Percent Margin of Error!!RACE!!Total population',
 'Estimate!!RACE!!Total population!!One race',
 'Margin of Error!!RACE!!Total population!!One race',
 'Percent!!RACE!!Total population!!One race',
 'Percent Margin of Error!!RACE!!Total population!!One race',
 'Estimate!!RACE!!Total population!!Two or more races',
 'Margin of Error!!RACE!!Total population!!Two or more races',
 'Percent!!RACE!!Total population!!Two or more races',
 'Percent Margin of Error!!RACE!!Total population!!Two or more races',
 'Estimate!!RACE!!Total population!!One race',
 'Margin of Error!!RACE!!Total population!!One race',
 'Percent!!RACE!!Total population!!One race',
 'Percent Margin of Error!!RACE!!Total population!!One race',
 'Estimate!!RACE!!Total population!!One race!!White',
 'Margin of Error!!RACE!!Total population!!One race!!White',
 'Percent!!RACE!!Total population!!One race!!White',
 'Percent Margin of Error!!RACE!!Total population!!One race!!White',
 'Estimate!!RACE!!Total population!!One race!!Black or African American',
 'Margin of Error!!RACE!!Total population!!One race!!Black or African American',
 'Percent!!RACE!!Total population!!One race!!Black or African American',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Black or African American',
 'Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native',
 'Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native',
 'Percent Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native',
 'Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Percent Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
 'Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Percent Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
 'Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Percent Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
 'Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Percent Margin of Error!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
 'Estimate!!RACE!!Total population!!One race!!Asian',
 'Margin of Error!!RACE!!Total population!!One race!!Asian',
 'Percent!!RACE!!Total population!!One race!!Asian',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian',
 'Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian',
 'Margin of Error!!RACE!!Total population!!One race!!Asian!!Asian Indian',
 'Percent!!RACE!!Total population!!One race!!Asian!!Asian Indian',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian!!Asian Indian',
 'Estimate!!RACE!!Total population!!One race!!Asian!!Chinese',
 'Margin of Error!!RACE!!Total population!!One race!!Asian!!Chinese',
 'Percent!!RACE!!Total population!!One race!!Asian!!Chinese',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian!!Chinese',
 'Estimate!!RACE!!Total population!!One race!!Asian!!Filipino',
 'Margin of Error!!RACE!!Total population!!One race!!Asian!!Filipino',
 'Percent!!RACE!!Total population!!One race!!Asian!!Filipino',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian!!Filipino',
 'Estimate!!RACE!!Total population!!One race!!Asian!!Japanese',
 'Margin of Error!!RACE!!Total population!!One race!!Asian!!Japanese',
 'Percent!!RACE!!Total population!!One race!!Asian!!Japanese',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian!!Japanese',
 'Estimate!!RACE!!Total population!!One race!!Asian!!Korean',
 'Margin of Error!!RACE!!Total population!!One race!!Asian!!Korean',
 'Percent!!RACE!!Total population!!One race!!Asian!!Korean',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian!!Korean',
 'Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese',
 'Margin of Error!!RACE!!Total population!!One race!!Asian!!Vietnamese',
 'Percent!!RACE!!Total population!!One race!!Asian!!Vietnamese',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian!!Vietnamese',
 'Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian',
 'Margin of Error!!RACE!!Total population!!One race!!Asian!!Other Asian',
 'Percent!!RACE!!Total population!!One race!!Asian!!Other Asian',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Asian!!Other Asian',
 'Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
 'Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
 'Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
 'Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Percent!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Estimate!!RACE!!Total population!!One race!!Some other race',
 'Margin of Error!!RACE!!Total population!!One race!!Some other race',
 'Percent!!RACE!!Total population!!One race!!Some other race',
 'Percent Margin of Error!!RACE!!Total population!!One race!!Some other race',
 'Estimate!!RACE!!Total population!!Two or more races',
 'Margin of Error!!RACE!!Total population!!Two or more races',
 'Percent!!RACE!!Total population!!Two or more races',
 'Percent Margin of Error!!RACE!!Total population!!Two or more races',
 'Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American',
 'Margin of Error!!RACE!!Total population!!Two or more races!!White and Black or African American',
 'Percent!!RACE!!Total population!!Two or more races!!White and Black or African American',
 'Percent Margin of Error!!RACE!!Total population!!Two or more races!!White and Black or African American',
 'Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native',
 'Margin of Error!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native',
 'Percent!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native',
 'Percent Margin of Error!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native',
 'Estimate!!RACE!!Total population!!Two or more races!!White and Asian',
 'Margin of Error!!RACE!!Total population!!Two or more races!!White and Asian',
 'Percent!!RACE!!Total population!!Two or more races!!White and Asian',
 'Percent Margin of Error!!RACE!!Total population!!Two or more races!!White and Asian',
 'Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Margin of Error!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Percent!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Percent Margin of Error!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native',
 'Estimate!!Race alone or in combination with one or more other races!!Total population',
 'Margin of Error!!Race alone or in combination with one or more other races!!Total population',
 'Percent!!Race alone or in combination with one or more other races!!Total population',
 'Percent Margin of Error!!Race alone or in combination with one or more other races!!Total population',
 'Estimate!!Race alone or in combination with one or more other races!!Total population!!White',
 'Margin of Error!!Race alone or in combination with one or more other races!!Total population!!White',
 'Percent!!Race alone or in combination with one or more other races!!Total population!!White',
 'Percent Margin of Error!!Race alone or in combination with one or more other races!!Total population!!White',
 'Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American',

In [6]:
# select desired columns
demo_df = demo_df[['Geographic Area Name','Estimate!!SEX AND AGE!!Total population','Estimate!!SEX AND AGE!!Total population!!Male','Estimate!!SEX AND AGE!!Total population!!Female','Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population','Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male','Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female']]
demo_df.head()

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female"
1,ZCTA5 37013,97939,47658,50281,59479,27984,31495
2,ZCTA5 37027,56117,27888,28229,39146,19094,20052
3,ZCTA5 37067,29543,14462,15081,20448,9573,10875
4,ZCTA5 37072,31492,15327,16165,24099,11489,12610
5,ZCTA5 37076,40161,19600,20561,30384,14353,16031

In [7]:
# rename headers of desired columns
demo_df = demo_df.rename(columns={'Geographic Area Name':'zip_code',
                                  'Estimate!!SEX AND AGE!!Total population':'total_population',
                                  'Estimate!!SEX AND AGE!!Total population!!Male':'total_male_population',
                                  'Estimate!!SEX AND AGE!!Total population!!Female':'total_female_popularion',
                                  'Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population':'18+',
                                  'Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male':'18+Male',
                                  'Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female':'18+Female'})

demo_df.head()

,zip_code,total_population,total_male_population,total_female_popularion,18+,18+Male,18+Female
1,ZCTA5 37013,97939,47658,50281,59479,27984,31495
2,ZCTA5 37027,56117,27888,28229,39146,19094,20052
3,ZCTA5 37067,29543,14462,15081,20448,9573,10875
4,ZCTA5 37072,31492,15327,16165,24099,11489,12610
5,ZCTA5 37076,40161,19600,20561,30384,14353,16031

In [8]:
# split geographica area name column to remove zcta5
text = demo_df['zip_code'].str.split(' ', n=1, expand=True)
demo_df['text']=text[0]
demo_df['zip_code']=text[1]
demo_df=demo_df.drop(columns='text')
demo_df.head()

,zip_code,total_population,total_male_population,total_female_popularion,18+,18+Male,18+Female
1,37013,97939,47658,50281,59479,27984,31495
2,37027,56117,27888,28229,39146,19094,20052
3,37067,29543,14462,15081,20448,9573,10875
4,37072,31492,15327,16165,24099,11489,12610
5,37076,40161,19600,20561,30384,14353,16031

In [9]:
# inspect edu_df headers
edu_df.head()

,GEO_ID,NAME,S1501_C01_001E,S1501_C01_001M,S1501_C01_002E,S1501_C01_002M,S1501_C01_003E,S1501_C01_003M,S1501_C01_004E,S1501_C01_004M,...,S1501_C06_060E,S1501_C06_060M,S1501_C06_061E,S1501_C06_061M,S1501_C06_062E,S1501_C06_062M,S1501_C06_063E,S1501_C06_063M,S1501_C06_064E,S1501_C06_064M
0,id,Geographic Area Name,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT...,Margin of Error!!Total!!AGE BY EDUCATIONAL ATT...,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT...,Margin of Error!!Total!!AGE BY EDUCATIONAL ATT...,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT...,Margin of Error!!Total!!AGE BY EDUCATIONAL ATT...,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT...,Margin of Error!!Total!!AGE BY EDUCATIONAL ATT...,...,Estimate!!Percent Female!!MEDIAN EARNINGS IN T...,Margin of Error!!Percent Female!!MEDIAN EARNIN...,Estimate!!Percent Female!!MEDIAN EARNINGS IN T...,Margin of Error!!Percent Female!!MEDIAN EARNIN...,Estimate!!Percent Female!!MEDIAN EARNINGS IN T...,Margin of Error!!Percent Female!!MEDIAN EARNIN...,Estimate!!Percent Female!!MEDIAN EARNINGS IN T...,Margin of Error!!Percent Female!!MEDIAN EARNIN...,Estimate!!Percent Female!!MEDIAN EARNINGS IN T...,Margin of Error!!Percent Female!!MEDIAN EARNIN...
1,8600000US37013,ZCTA5 37013,9099,858,1073,278,3288,392,3382,632,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
2,8600000US37027,ZCTA5 37027,4292,594,643,171,799,214,1621,353,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
3,8600000US37067,ZCTA5 37067,2278,524,227,150,819,348,440,165,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
4,8600000US37072,ZCTA5 37072,2230,344,336,145,773,208,810,228,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)

In [10]:
# change header to 1st row edu_df
new_header = edu_df.iloc[0] # assign index 0 as variable
edu_df = edu_df[1:]  # drops orriginal headers
edu_df.columns = new_header # assigns header to previous index 0
edu_df.head()

,id,Geographic Area Name,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years,Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate,Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency),Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency),Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree,Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree,...,Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Less than high school graduate,Margin of Error!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Less than high school graduate,Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!High school graduate (includes equivalency),Margin of Error!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!High school graduate (includes equivalency),Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Some college or associate's degree,Margin of Error!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Some college or associate's degree,Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Bachelor's degree,Margin of Error!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Bachelor's degree,Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Margin of Error!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree
1,8600000US37013,ZCTA5 37013,9099,858,1073,278,3288,392,3382,632,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
2,8600000US37027,ZCTA5 37027,4292,594,643,171,799,214,1621,353,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
3,8600000US37067,ZCTA5 37067,2278,524,227,150,819,348,440,165,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
4,8600000US37072,ZCTA5 37072,2230,344,336,145,773,208,810,228,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
5,8600000US37076,ZCTA5 37076,3191,476,278,134,740,265,1577,314,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)

In [11]:
# view all headers
list(edu_df.columns.values)

['id',
 'Geographic Area Name',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree",
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher",
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree",
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree",
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher",
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher",
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher",
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher",
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over',
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher',
 'Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher",
 "Margin of Error!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!American Indian or Alaska Native alone!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Asian alone!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Native Hawaiian and Other Pacific Islander alone!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!Bachelor's degree or higher",
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin',
 'Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!High school graduate or higher',
 'Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!High school graduate or higher',
 "Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!Bachelor's degree or higher",
 "Margin of Error!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!Bachelor's degree or higher",
 'Estimate!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Margin of Error!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate',
 'Estimate!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 'Margin of Error!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency)',
 "Estimate!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Margin of Error!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree",
 "Estimate!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 "Margin of Error!!Total!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher",
 'Estimate!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Margin of Error!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings',
 'Estimate!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Less than high school graduate',
 'Margin of Error!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Less than high school graduate',
 'Estimate!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!High school graduate (includes equivalency)',
 'Margin of Error!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!High school graduate (includes equivalency)',
 "Estimate!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Some college or associate's degree",
 "Margin of Error!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Some college or associate's degree",
 "Estimate!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Bachelor's degree",
 "Margin of Error!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Bachelor's degree",
 'Estimate!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree',
 'Margin of Error!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)',
 "Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree",
 "Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree",
 "Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher",
 "Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher",
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Less than 9th grade',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!9th to 12th grade, no diploma',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate (includes equivalency)',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Some college, no degree',
 "Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree",
 "Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Associate's degree",
 "Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree",
 "Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree",
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Graduate or professional degree',
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!High school graduate or higher',
 "Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher",
 "Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher",
 'Estimate!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years',
 'Margin of Error!!Percent!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years',

In [12]:
# select desired columns
edu_df=edu_df[["Geographic Area Name",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher",
              "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher"]]
edu_df.head()

,Geographic Area Name,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency),Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher
1,ZCTA5 37013,9099,1073,3288,3382,1356,19538,18099,7976,14718,12572,4892,21411,18469,6284,6688,5643,1395
2,ZCTA5 37027,4292,643,799,1621,1229,4309,4295,3348,7336,7153,6170,16799,16560,12819,8181,7965,5097
3,ZCTA5 37067,2278,227,819,440,792,4046,4009,3107,4382,4237,3424,8494,8330,5496,3696,3470,1539
4,ZCTA5 37072,2230,336,773,810,311,5008,4695,1924,3067,2898,1048,8761,7767,2363,5843,5063,1181
5,ZCTA5 37076,3191,278,740,1577,596,7422,7093,3693,6216,5633,2611,10036,9179,3243,5114,4688,1268

In [13]:
# split geographic area name to remove ZCTA5
text_1 = edu_df['Geographic Area Name'].str.split(' ', n=1, expand=True)
edu_df['text']=text_1[0]
edu_df['Geographic Area Name']=text_1[1]
edu_df=edu_df.drop(columns='text')
edu_df.head()

,Geographic Area Name,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency),Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher
1,37013,9099,1073,3288,3382,1356,19538,18099,7976,14718,12572,4892,21411,18469,6284,6688,5643,1395
2,37027,4292,643,799,1621,1229,4309,4295,3348,7336,7153,6170,16799,16560,12819,8181,7965,5097
3,37067,2278,227,819,440,792,4046,4009,3107,4382,4237,3424,8494,8330,5496,3696,3470,1539
4,37072,2230,336,773,810,311,5008,4695,1924,3067,2898,1048,8761,7767,2363,5843,5063,1181
5,37076,3191,278,740,1577,596,7422,7093,3693,6216,5633,2611,10036,9179,3243,5114,4688,1268

In [14]:
# change datatype to numeric
edu_df = edu_df.astype(int)

In [15]:
# create new columns combining columns for desired datapoints
edu_df['18-24 highschool']= edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency)"] + edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree"]
edu_df['25-34 not high school graduate'] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years"]-edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher"]
edu_df['25-34 high school graduate']=edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher"] - edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher"]
edu_df['35-44 not high school graduate'] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years"] - edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher"]
edu_df['35-44 high school graduate'] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!High school graduate or higher"] - edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher"]
edu_df['45-64 not high school graduate'] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years"]-edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher"]
edu_df['45-64 high school graduate'] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!High school graduate or higher"] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher"]
edu_df['65 and up not high school graduate'] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over"] - edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher"]
edu_df['65 and up high school graduate'] = edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!High school graduate or higher"] - edu_df["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher"]
edu_df.head()

,Geographic Area Name,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!High school graduate (includes equivalency),Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Some college or associate's degree,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!High school graduate or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years,...,Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher,18-24 highschool,25-34 not high school graduate,25-34 high school graduate,35-44 not high school graduate,35-44 high school graduate,45-64 not high school graduate,45-64 high school graduate,65 and up not high school graduate,65 and up high school graduate
1,37013,9099,1073,3288,3382,1356,19538,18099,7976,14718,...,1395,6670,1439,10123,2146,7680,2942,6284,1045,4248
2,37027,4292,643,799,1621,1229,4309,4295,3348,7336,...,5097,2420,14,947,183,983,239,12819,216,2868
3,37067,2278,227,819,440,792,4046,4009,3107,4382,...,1539,1259,37,902,145,813,164,5496,226,1931
4,37072,2230,336,773,810,311,5008,4695,1924,3067,...,1181,1583,313,2771,169,1850,994,2363,780,3882
5,37076,3191,278,740,1577,596,7422,7093,3693,6216,...,1268,2317,329,3400,583,3022,857,3243,426,3420

In [16]:
# change column names
edu_df = edu_df.rename(columns={"Geographic Area Name":"zip_code",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years":"Population 18-24",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Less than high school graduate":"18-24 not high school graduate",
                                "18-24 highschool" : "18-24 high school graduate",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher":"18-24 bachelor's degree or higher",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years":"Population 25 to 34 years",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years":"Population 35 to 44 years",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over":"Population 65 and up",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 to 34 years!!Bachelor's degree or higher":"25-34 Bachelor's or higher",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 35 to 44 years!!Bachelor's degree or higher":"35-44 Bachelor's or higher",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 45 to 64 years!!Bachelor's degree or higher":"45-64 Bachelor's or higher",
                                "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 65 years and over!!Bachelor's degree or higher":"65 and up Bachelor's or higher"
})

In [17]:
# select desired columns
edu_df = edu_df[["zip_code","Population 18-24","18-24 not high school graduate","18-24 high school graduate","18-24 bachelor's degree or higher","Population 25 to 34 years","25-34 not high school graduate","25-34 high school graduate","25-34 Bachelor's or higher","Population 35 to 44 years","35-44 not high school graduate","35-44 high school graduate","35-44 Bachelor's or higher","Population 65 and up","65 and up not high school graduate","65 and up high school graduate","65 and up Bachelor's or higher"]]
edu_df.head()

,zip_code,Population 18-24,18-24 not high school graduate,18-24 high school graduate,18-24 bachelor's degree or higher,Population 25 to 34 years,25-34 not high school graduate,25-34 high school graduate,25-34 Bachelor's or higher,Population 35 to 44 years,35-44 not high school graduate,35-44 high school graduate,35-44 Bachelor's or higher,Population 65 and up,65 and up not high school graduate,65 and up high school graduate,65 and up Bachelor's or higher
1,37013,9099,1073,6670,1356,19538,1439,10123,7976,14718,2146,7680,4892,6688,1045,4248,1395
2,37027,4292,643,2420,1229,4309,14,947,3348,7336,183,983,6170,8181,216,2868,5097
3,37067,2278,227,1259,792,4046,37,902,3107,4382,145,813,3424,3696,226,1931,1539
4,37072,2230,336,1583,311,5008,313,2771,1924,3067,169,1850,1048,5843,780,3882,1181
5,37076,3191,278,2317,596,7422,329,3400,3693,6216,583,3022,2611,5114,426,3420,1268

In [18]:
# set dtype back to object
# change datatype to numeric
edu_df = edu_df.astype(object)

In [19]:
# inspect headers income_df
income_df.head()

,GEO_ID,NAME,S1902_C01_001E,S1902_C01_001M,S1902_C01_002E,S1902_C01_002M,S1902_C01_003E,S1902_C01_003M,S1902_C01_004E,S1902_C01_004M,...,S1902_C03_024E,S1902_C03_024M,S1902_C03_025E,S1902_C03_025M,S1902_C03_026E,S1902_C03_026M,S1902_C03_027E,S1902_C03_027M,S1902_C03_028E,S1902_C03_028M
0,id,Geographic Area Name,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,Estimate!!Number!!HOUSEHOLD INCOME!!All househ...,Margin of Error!!Number!!HOUSEHOLD INCOME!!All...,...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...,Estimate!!Mean income (dollars)!!PER CAPITA IN...,Margin of Error!!Mean income (dollars)!!PER CA...
1,8600000US37013,ZCTA5 37013,35597,617,32387,719,31604,740,3287,434,...,-,**,17628,4083,17374,3088,16338,1568,30636,1594
2,8600000US37027,ZCTA5 37027,19950,382,17187,405,16433,396,3924,363,...,-,**,37496,17308,43565,37050,54496,13759,73457,3110
3,8600000US37067,ZCTA5 37067,11643,361,10291,369,9916,373,1835,264,...,-,**,13467,11489,57728,25043,31515,10201,57291,3730
4,8600000US37072,ZCTA5 37072,12533,464,9964,490,9627,504,1345,250,...,N,N,20772,8292,20154,6360,16520,4385,36295,3311

In [20]:
# change header to 1st row edu_df
new_header = income_df.iloc[0]
income_df = income_df[1:]  #drops orriginal headers
income_df.columns = new_header
income_df.head()

,id,Geographic Area Name,Estimate!!Number!!HOUSEHOLD INCOME!!All households,Margin of Error!!Number!!HOUSEHOLD INCOME!!All households,Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With earnings,Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With earnings,Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income,Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income,Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income,Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income,...,Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander,Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander,Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race,Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race,Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races,Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races,Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race),Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race),"Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!White alone, not Hispanic or Latino","Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!White alone, not Hispanic or Latino"
1,8600000US37013,ZCTA5 37013,35597,617,32387,719,31604,740,3287,434,...,-,**,17628,4083,17374,3088,16338,1568,30636,1594
2,8600000US37027,ZCTA5 37027,19950,382,17187,405,16433,396,3924,363,...,-,**,37496,17308,43565,37050,54496,13759,73457,3110
3,8600000US37067,ZCTA5 37067,11643,361,10291,369,9916,373,1835,264,...,-,**,13467,11489,57728,25043,31515,10201,57291,3730
4,8600000US37072,ZCTA5 37072,12533,464,9964,490,9627,504,1345,250,...,N,N,20772,8292,20154,6360,16520,4385,36295,3311
5,8600000US37076,ZCTA5 37076,17389,393,14751,512,14204,483,2224,338,...,-,**,15396,7024,22150,8401,15014,2659,38378,1510

In [21]:
# view all headers
list(income_df.columns.values)

['id',
 'Geographic Area Name',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With earnings',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With earnings',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With interest, dividends, or net rental income',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With interest, dividends, or net rental income',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With Social Security income',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With Social Security income',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With Supplemental Security Income (SSI)',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With Supplemental Security Income (SSI)',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP!!With cash public assistance',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP!!With cash public assistance',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With retirement income',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With retirement income',
 'Estimate!!Number!!HOUSEHOLD INCOME!!All households!!With other types of income',
 'Margin of Error!!Number!!HOUSEHOLD INCOME!!All households!!With other types of income',
 'Estimate!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families',
 'Margin of Error!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families',
 'Estimate!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!No workers',
 'Margin of Error!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!No workers',
 'Estimate!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!1 worker',
 'Margin of Error!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!1 worker',
 'Estimate!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, both spouses worked',
 'Margin of Error!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, both spouses worked',
 'Estimate!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, other',
 'Margin of Error!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, other',
 'Estimate!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, both spouses worked',
 'Margin of Error!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, both spouses worked',
 'Estimate!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, other',
 'Margin of Error!!Number!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, other',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!White',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!White',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Black or African American',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Black or African American',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!American Indian and Alaska Native',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!American Indian and Alaska Native',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Asian',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Asian',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race)',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race)',
 'Estimate!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!White alone, not Hispanic or Latino',
 'Margin of Error!!Number!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!White alone, not Hispanic or Latino',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With earnings',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With earnings',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With interest, dividends, or net rental income',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With interest, dividends, or net rental income',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With Social Security income',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With Social Security income',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With Supplemental Security Income (SSI)',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With Supplemental Security Income (SSI)',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP!!With cash public assistance',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP!!With cash public assistance',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With retirement income',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With retirement income',
 'Estimate!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With other types of income',
 'Margin of Error!!Percent Distribution!!HOUSEHOLD INCOME!!All households!!With other types of income',
 'Estimate!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families',
 'Margin of Error!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families',
 'Estimate!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!No workers',
 'Margin of Error!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!No workers',
 'Estimate!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!1 worker',
 'Margin of Error!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!1 worker',
 'Estimate!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, both spouses worked',
 'Margin of Error!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, both spouses worked',
 'Estimate!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, other',
 'Margin of Error!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, other',
 'Estimate!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, both spouses worked',
 'Margin of Error!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, both spouses worked',
 'Estimate!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, other',
 'Margin of Error!!Percent Distribution!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, other',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!White',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!White',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Black or African American',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Black or African American',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!American Indian and Alaska Native',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!American Indian and Alaska Native',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Asian',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Asian',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race)',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race)',
 'Estimate!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!White alone, not Hispanic or Latino',
 'Margin of Error!!Percent Distribution!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!White alone, not Hispanic or Latino',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With earnings',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With earnings',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With earnings!!With wages or salary income',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With earnings!!With self-employment income',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With interest, dividends, or net rental income',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With interest, dividends, or net rental income',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With Social Security income',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With Social Security income',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With Supplemental Security Income (SSI)',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With Supplemental Security Income (SSI)',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP!!With cash public assistance',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With cash public assistance income or Food Stamps/SNAP!!With cash public assistance',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With retirement income',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With retirement income',
 'Estimate!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With other types of income',
 'Margin of Error!!Mean income (dollars)!!HOUSEHOLD INCOME!!All households!!With other types of income',
 'Estimate!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families',
 'Margin of Error!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families',
 'Estimate!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!No workers',
 'Margin of Error!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!No workers',
 'Estimate!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!1 worker',
 'Margin of Error!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!1 worker',
 'Estimate!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, both spouses worked',
 'Margin of Error!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, both spouses worked',
 'Estimate!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, other',
 'Margin of Error!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!2 workers, other',
 'Estimate!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, both spouses worked',
 'Margin of Error!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, both spouses worked',
 'Estimate!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, other',
 'Margin of Error!!Mean income (dollars)!!FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY!!All families!!3 or more workers, other',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!White',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!White',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Black or African American',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Black or African American',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!American Indian and Alaska Native',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!American Indian and Alaska Native',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Asian',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Asian',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Native Hawaiian and Other Pacific Islander',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!One race--!!Some other race',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Two or more races',
 'Estimate!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race)',
 'Margin of Error!!Mean income (dollars)!!PER CAPITA INCOME BY RACE AND HISPANIC OR LATINO ORIGIN!!Total population!!Hispanic or Latino origin (of any race)',

In [22]:
# select columns to keep
income_df = income_df[["Geographic Area Name","Estimate!!Number!!HOUSEHOLD INCOME!!All households"]]
income_df.head()

0 Geographic Area Name Estimate!!Number!!HOUSEHOLD INCOME!!All households
1          ZCTA5 37013                                              35597
2          ZCTA5 37027                                              19950
3          ZCTA5 37067                                              11643
4          ZCTA5 37072                                              12533
5          ZCTA5 37076                                              17389

In [23]:
# change name of Geographic Area Name column to zip_code
income_df = income_df.rename(columns={"Geographic Area Name":"zip_code",
                                "Estimate!!Number!!HOUSEHOLD INCOME!!All households":"average household income"})

In [24]:
# split zip_code to remove ZCTA5
text_2 = income_df['zip_code'].str.split(' ', n=1, expand=True)
income_df['text']=text_1[0]
income_df['zip_code']=text_2[1]
income_df=income_df.drop(columns='text')
income_df.head()

0 zip_code average household income
1    37013                    35597
2    37027                    19950
3    37067                    11643
4    37072                    12533
5    37076                    17389

In [25]:
len(demo_df)

32

In [26]:
len(income_df)

32

In [27]:
len(edu_df)

32

In [28]:
demo_df.dtypes

0
zip_code                   object
total_population           object
total_male_population      object
total_female_popularion    object
18+                        object
18+Male                    object
18+Female                  object
dtype: object

In [29]:
edu_df.dtypes

0
zip_code                              object
Population 18-24                      object
18-24 not high school graduate        object
18-24 high school graduate            object
18-24 bachelor's degree or higher     object
Population 25 to 34 years             object
25-34 not high school graduate        object
25-34 high school graduate            object
25-34 Bachelor's or higher            object
Population 35 to 44 years             object
35-44 not high school graduate        object
35-44 high school graduate            object
35-44 Bachelor's or higher            object
Population 65 and up                  object
65 and up not high school graduate    object
65 and up high school graduate        object
65 and up Bachelor's or higher        object
dtype: object

In [30]:
income_df.dtypes

0
zip_code                    object
average household income    object
dtype: object

In [34]:
demo_df['zip_code']=pd.to_numeric(demo_df['zip_code'])
edu_df['zip_code']=pd.to_numeric(edu_df['zip_code'])
income_df['zip_code']=pd.to_numeric(income_df['zip_code'])

In [35]:
# join demo adn edu dataframes on zip code
merged_df = demo_df.merge(edu_df, on='zip_code')
#merged_df['zip_code']=pd.to_numeric(merged_df['zip_code'])
merged_df.sort_values(by='zip_code')
#.merge(income_df, on="zip_code")
merged_df

,zip_code,total_population,total_male_population,total_female_popularion,18+,18+Male,18+Female,Population 18-24,18-24 not high school graduate,18-24 high school graduate,...,25-34 high school graduate,25-34 Bachelor's or higher,Population 35 to 44 years,35-44 not high school graduate,35-44 high school graduate,35-44 Bachelor's or higher,Population 65 and up,65 and up not high school graduate,65 and up high school graduate,65 and up Bachelor's or higher
0,37013,97939,47658,50281,59479,27984,31495,9099,1073,6670,...,10123,7976,14718,2146,7680,4892,6688,1045,4248,1395
1,37027,56117,27888,28229,39146,19094,20052,4292,643,2420,...,947,3348,7336,183,983,6170,8181,216,2868,5097
2,37067,29543,14462,15081,20448,9573,10875,2278,227,1259,...,902,3107,4382,145,813,3424,3696,226,1931,1539
3,37072,31492,15327,16165,24099,11489,12610,2230,336,1583,...,2771,1924,3067,169,1850,1048,5843,780,3882,1181
4,37076,40161,19600,20561,30384,14353,16031,3191,278,2317,...,3400,3693,6216,583,3022,2611,5114,426,3420,1268
5,37078,380,194,186,350,174,176,67,7,60,...,13,21,48,6,35,7,102,9,86,7
6,37080,7394,3703,3691,5988,3076,2912,509,136,336,...,528,157,713,151,387,175,1387,401,792,194
7,37115,40343,19376,20967,27390,12606,14784,3166,728,2308,...,3880,1514,5435,1127,3346,962,5289,872,3444,973
8,37135,14256,6919,7337,9515,4777,4738,1165,248,831,...,381,826,2503,37,691,1775,1155,103,576,476
9,37138,23784,11320,12464,17799,8591,9208,1229,238,832,...,1252,1143,3653,392,2010,1251,3798,711,2177,910
10,37189,4016,1642,2374,3196,1283,1913,100,5,78,...,353,222,799,38,325,436,722,72,479,171
11,37201,1619,1245,374,1475,1132,343,301,98,191,...,249,200,245,33,141,71,88,0,56,32
12,37203,15091,7412,7679,12679,6154,6525,2420,157,1191,...,1321,4193,1799,166,404,1229,1121,346,551,224
13,37204,15452,6908,8544,12294,5498,6796,2737,73,2208,...,662,3075,1947,8,342,1597,1274,175,393,706
14,37205,23790,10824,12966,19366,8780,10586,1837,181,822,...,549,2986,2661,36,349,2276,5518,224,1774,3520
15,37206,26382,12473,13909,20213,9555,10658,1990,228,1435,...,2506,4186,4208,364,1408,2436,2226,450,1369,407
16,37207,39544,17866,21678,27146,11945,15201,3010,363,2408,...,3863,1750,5220,749,3263,1208,4632,1105,2609,918
17,37208,18011,7917,10094,13835,5881,7954,2376,190,1794,...,1133,2517,2324,387,1157,780,1795,542,961,292
18,37209,38664,18251,20413,29326,13363,15963,5522,337,3591,...,3399,7262,4738,744,2011,1983,3052,554,1801,697
19,37210,17248,8731,8517,11023,5157,5866,2256,163,1811,...,1512,1461,2026,473,1095,458,1691,453,968,270
20,37211,75955,39340,36615,46637,23496,23141,6972,1130,4261,...,6777,7978,10945,2185,4461,4299,7558,1278,4203,2077
21,37212,20803,9757,11046,16969,7878,9091,7760,110,6647,...,822,3235,1808,115,277,1416,1541,168,583,790
22,37213,95,86,9,76,76,0,0,0,0,...,54,0,12,0,0,12,0,0,0,0
23,37214,30528,14968,15560,24025,11392,12633,2053,240,1460,...,2779,3304,4864,180,2388,2296,4103,528,2624,951
24,37215,22379,9989,12390,17874,7986,9888,1774,222,848,...,434,2246,2488,24,378,2086,5135,121,1211,3803
25,37216,17848,8877,8971,14856,7510,7346,1179,129,777,...,1550,2607,2828,140,1382,1306,2311,414,1295,602
26,37217,30146,15018,15128,18346,8998,9348,2633,347,1786,...,3346,2215,4507,559,2537,1411,2772,473,1591,708
27,37218,15721,7083,8638,12126,5319,6807,849,88,696,...,1263,639,2150,196,1302,652,3024,547,1754,723
28,37219,1154,737,417,1111,724,387,201,0,13,...,70,166,180,0,18,162,114,0,0,114
29,37220,5880,2994,2886,4479,2126,2353,217,72,65,...,147,368,865,0,121,744,1143,0,498,645
30,37221,41017,19437,21580,31187,13925,17262,2748,179,1866,...,2023,4585,5230,256,1830,3144,6499,370,3232,2897
31,37228,1615,708,907,1518,665,853,354,0,278,...,149,302,88,0,17,71,450,187,217,46

In [36]:
# join merged and income df on zip codes
merged_df = merged_df.merge(income_df, on='zip_code')
merged_df.sort_values(by='zip_code')
merged_df

,zip_code,total_population,total_male_population,total_female_popularion,18+,18+Male,18+Female,Population 18-24,18-24 not high school graduate,18-24 high school graduate,...,25-34 Bachelor's or higher,Population 35 to 44 years,35-44 not high school graduate,35-44 high school graduate,35-44 Bachelor's or higher,Population 65 and up,65 and up not high school graduate,65 and up high school graduate,65 and up Bachelor's or higher,average household income
0,37013,97939,47658,50281,59479,27984,31495,9099,1073,6670,...,7976,14718,2146,7680,4892,6688,1045,4248,1395,35597
1,37027,56117,27888,28229,39146,19094,20052,4292,643,2420,...,3348,7336,183,983,6170,8181,216,2868,5097,19950
2,37067,29543,14462,15081,20448,9573,10875,2278,227,1259,...,3107,4382,145,813,3424,3696,226,1931,1539,11643
3,37072,31492,15327,16165,24099,11489,12610,2230,336,1583,...,1924,3067,169,1850,1048,5843,780,3882,1181,12533
4,37076,40161,19600,20561,30384,14353,16031,3191,278,2317,...,3693,6216,583,3022,2611,5114,426,3420,1268,17389
5,37078,380,194,186,350,174,176,67,7,60,...,21,48,6,35,7,102,9,86,7,163
6,37080,7394,3703,3691,5988,3076,2912,509,136,336,...,157,713,151,387,175,1387,401,792,194,3012
7,37115,40343,19376,20967,27390,12606,14784,3166,728,2308,...,1514,5435,1127,3346,962,5289,872,3444,973,16510
8,37135,14256,6919,7337,9515,4777,4738,1165,248,831,...,826,2503,37,691,1775,1155,103,576,476,4476
9,37138,23784,11320,12464,17799,8591,9208,1229,238,832,...,1143,3653,392,2010,1251,3798,711,2177,910,9264
10,37189,4016,1642,2374,3196,1283,1913,100,5,78,...,222,799,38,325,436,722,72,479,171,1509
11,37201,1619,1245,374,1475,1132,343,301,98,191,...,200,245,33,141,71,88,0,56,32,526
12,37203,15091,7412,7679,12679,6154,6525,2420,157,1191,...,4193,1799,166,404,1229,1121,346,551,224,8726
13,37204,15452,6908,8544,12294,5498,6796,2737,73,2208,...,3075,1947,8,342,1597,1274,175,393,706,5962
14,37205,23790,10824,12966,19366,8780,10586,1837,181,822,...,2986,2661,36,349,2276,5518,224,1774,3520,10778
15,37206,26382,12473,13909,20213,9555,10658,1990,228,1435,...,4186,4208,364,1408,2436,2226,450,1369,407,11550
16,37207,39544,17866,21678,27146,11945,15201,3010,363,2408,...,1750,5220,749,3263,1208,4632,1105,2609,918,14909
17,37208,18011,7917,10094,13835,5881,7954,2376,190,1794,...,2517,2324,387,1157,780,1795,542,961,292,7974
18,37209,38664,18251,20413,29326,13363,15963,5522,337,3591,...,7262,4738,744,2011,1983,3052,554,1801,697,15884
19,37210,17248,8731,8517,11023,5157,5866,2256,163,1811,...,1461,2026,473,1095,458,1691,453,968,270,6967
20,37211,75955,39340,36615,46637,23496,23141,6972,1130,4261,...,7978,10945,2185,4461,4299,7558,1278,4203,2077,29450
21,37212,20803,9757,11046,16969,7878,9091,7760,110,6647,...,3235,1808,115,277,1416,1541,168,583,790,6957
22,37213,95,86,9,76,76,0,0,0,0,...,0,12,0,0,12,0,0,0,0,22
23,37214,30528,14968,15560,24025,11392,12633,2053,240,1460,...,3304,4864,180,2388,2296,4103,528,2624,951,13894
24,37215,22379,9989,12390,17874,7986,9888,1774,222,848,...,2246,2488,24,378,2086,5135,121,1211,3803,9998
25,37216,17848,8877,8971,14856,7510,7346,1179,129,777,...,2607,2828,140,1382,1306,2311,414,1295,602,7923
26,37217,30146,15018,15128,18346,8998,9348,2633,347,1786,...,2215,4507,559,2537,1411,2772,473,1591,708,12470
27,37218,15721,7083,8638,12126,5319,6807,849,88,696,...,639,2150,196,1302,652,3024,547,1754,723,5854
28,37219,1154,737,417,1111,724,387,201,0,13,...,166,180,0,18,162,114,0,0,114,829
29,37220,5880,2994,2886,4479,2126,2353,217,72,65,...,368,865,0,121,744,1143,0,498,645,2316
30,37221,41017,19437,21580,31187,13925,17262,2748,179,1866,...,4585,5230,256,1830,3144,6499,370,3232,2897,17959
31,37228,1615,708,907,1518,665,853,354,0,278,...,302,88,0,17,71,450,187,217,46,1051

In [37]:
# export csv files
income_df.to_csv("Resources/income_data_clean.csv")
edu_df.to_csv("Resources/education_data_clean.csv")
demo_df.to_csv("Resources/demographic_data_clean.csv")

In [38]:
# export merged dataframe
merged_df.to_csv("Resources/all_demographic_data_merged.csv")

In [39]:
list(merged_df.columns.values)

['zip_code',
 'total_population',
 'total_male_population',
 'total_female_popularion',
 '18+',
 '18+Male',
 '18+Female',
 'Population 18-24',
 '18-24 not high school graduate',
 '18-24 high school graduate',
 "18-24 bachelor's degree or higher",
 'Population 25 to 34 years',
 '25-34 not high school graduate',
 '25-34 high school graduate',
 "25-34 Bachelor's or higher",
 'Population 35 to 44 years',
 '35-44 not high school graduate',
 '35-44 high school graduate',
 "35-44 Bachelor's or higher",
 'Population 65 and up',
 '65 and up not high school graduate',
 '65 and up high school graduate',
 "65 and up Bachelor's or higher",
 'average household income']